// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Abhishek Kadavil",
            "url": "https://github.com/abhishekkadavil/golang-gin-crud",
            "email": "abhishek.kadavil@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/employee/create": {
            "post": {
                "description": "Save employee data in Db.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee CRUD"
                ],
                "summary": "Create employee",
                "responses": {}
            }
        },
        "/employees": {
            "get": {
                "description": "Get all employees data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee CRUD"
                ],
                "summary": "Get all employees",
                "responses": {}
            }
        },
        "/employees/{id}": {
            "get": {
                "description": "Get an employees data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee CRUD"
                ],
                "summary": "Get an employee",
                "responses": {}
            },
            "put": {
                "description": "Update an employees data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee CRUD"
                ],
                "summary": "Update an employee",
                "responses": {}
            },
            "delete": {
                "description": "Delete an employees data from Db.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee CRUD"
                ],
                "summary": "Delete an employee",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Golang Gin CRUD API",
	Description:      "Simple CRUD operation APIs in Golang Gin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
